# This file was generated by the {rix} R package v0.18.2 on 2026-09-28
# with following call:
# >rix::rix(r_ver = "4.6.1",
#  > r_pkgs = c("ape",
#  > "BiocBook",
#  > "BiocManager",
#  > "BiocStyle",
#  > "bluster",
#  > "ComplexHeatmap",
#  > "curatedMetagenomicData",
#  > "dendextend",
#  > "DirichletMultinomial",
#  > "dplyr",
#  > "DT",
#  > "factoextra",
#  > "ggdag",
#  > "ggExtra",
#  > "ggplot2",
#  > "ggpubr",
#  > "ggtree",
#  > "glue",
#  > "gt",
#  > "knitr",
#  > "Maaslin2",
#  > "maaslin3",
#  > "mediation",
#  > "mia",
#  > "miaTime",
#  > "miaViz",
#  > "microbiomeDataSets",
#  > "mikropml",
#  > "MOFA2",
#  > "NbClust",
#  > "NMF",
#  > "patchwork",
#  > "philr",
#  > "phyloseq",
#  > "qgraph",
#  > "rebook",
#  > "scales",
#  > "scater",
#  > "scuttle",
#  > "sechm",
#  > "sessioninfo",
#  >      "shadowtext",
#  > "tidySingleCellExperiment",
#  > "tidyverse",
#  > "vegan"),
#  > system_pkgs = c("quarto",
#  > "radian"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-09-23.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ape
      BiocBook
      BiocManager
      BiocStyle
      bluster
      ComplexHeatmap
      curatedMetagenomicData
      dendextend
      DirichletMultinomial
      dplyr
      DT
      factoextra
      ggdag
      ggExtra
      ggplot2
      ggpubr
      ggtree
      glue
      gt
      knitr
      Maaslin2
      maaslin3
      mediation
      mia
      miaTime
      miaViz
      microbiomeDataSets
      mikropml
      MOFA2
      NbClust
      NMF
      patchwork
      philr
      phyloseq
      qgraph
      rebook
      scales
      scater
      scuttle
      sechm
      sessioninfo
      shadowtext
      tidySingleCellExperiment
      tidyverse
      vegan;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R
      radian;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
