rix::rix(
  r_ver = "4.6.1",
  r_pkgs = c(
    "ape",
    "BiocBook",
    "BiocManager",
    "BiocStyle",
    "bluster",
    "ComplexHeatmap",
    "curatedMetagenomicData",
    "dendextend",
    "DirichletMultinomial",
    "dplyr",
    "DT",
    "GenomeInfoDb",
    "factoextra",
    "ggdag",
    "ggExtra",
    "ggplot2",
    "ggpubr",
    "ggtree",
    "glue",
    "gt",
    "knitr",
    "Maaslin2",
    "maaslin3",
    "mediation",
    "mia",
    "miaTime",
    "miaViz",
    "microbiomeDataSets",
    "mikropml",
    "MOFA2",
    "NbClust",
    "NMF",
    "patchwork",
    "philr",
    "phyloseq",
    "qgraph",
    "rebook",
    "rix",
    "scales",
    "scater",
    "scuttle",
    "sechm",
    "sessioninfo",
    "shadowtext",
    "tidySingleCellExperiment",
    "tidyverse",
    "vegan"
  ),
  system_pkgs = c("quarto", "radian"),
  ide = "none",
  project_path = ".",
  overwrite = TRUE
)
